import { mkdir, readFile, writeFile, readdir, copyFile } from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const source=path.resolve('source'), output=path.join(process.env.RUNNER_TEMP,'scaffold-diagnostic');
await mkdir(output,{recursive:true});
const {executeScaffoldSmoke}=await import(pathToFileURL(path.join(source,'scripts/release/smoke/scaffold.mjs')));
const {createStrictSmokeProcessRunner}=await import(pathToFileURL(path.join(source,'scripts/release/smoke-process-runner.mjs')));
const {publicNpmEnvironment}=await import(pathToFileURL(path.join(source,'scripts/lib/published-artifacts.mjs')));
const {readInstalledResolutions}=await import(pathToFileURL(path.join(source,'scripts/release/recovery/smoke.mjs')));
const {candidate}=JSON.parse(await readFile(path.join(source,'scripts/release/recovery-adoptions/v0.8.24.json'),'utf8'));
await writeFile(path.join(output,'NOTICE.txt'),`Diagnostic only. No recovery authority or receipt. Node ${process.version}, platform ${process.platform}. Source f18eb041e157ce42c281c9dad70b8a3c18290fa7.\n`);
const raw=createStrictSmokeProcessRunner();let seq=0;const roots=new Set(), cleanup=[];
async function log(name,value){const text=typeof value==='string'?value:JSON.stringify(value,null,2);await writeFile(path.join(output,name),text.slice(0,2*1024*1024)+'\n');}
const strictRunner={probe:()=>raw.probe(),async runCommand(command,args,options){const id=String(++seq).padStart(2,'0');roots.add(options.cwd);await log(id+'-command.txt',JSON.stringify({command,args,cwd:options.cwd}));try{const result=await raw.runCommand(command,args,options);await log(id+'-stdout.log',result.stdout);await log(id+'-stderr.log',result.stderr);return result;}catch(error){await log(id+'-error.log',error.stack+'\n'+(error.stderr??''));throw error;}}};
async function check(name,detail,action){console.log('START '+name);try{const result=await action();console.log('PASS '+name);return result;}catch(error){await log('failure-'+name+'.log',error.stack);console.error('FAIL '+name+'\n'+error.stack);throw error;}}
async function captureInstallation(name,root){console.log('CAPTURE npm-ls '+name);await strictRunner.runCommand('npm',['ls','--all','--json'],{cwd:root,env:publicNpmEnvironment({home:root}),timeoutMs:60000,maxOutputBytes:16*1024*1024});console.log('CAPTURE inventory '+name);try{const rows=await readInstalledResolutions(root,candidate);await log(name+'-inventory-summary.txt','Inventory rows: '+rows.length+'\nNo receipt or installation sidecar emitted.');console.log('CAPTURE PASS '+name+' '+rows.length);}catch(error){await log(name+'-inventory-error.log',error.stack);throw error;}}
try{await executeScaffoldSmoke({version:candidate.version},{check,deferCleanup:(name,detail,action)=>cleanup.push(action),captureInstallation},{strictRunner});await log('outcome.txt','All scaffold operations and inventory reads passed; receipt schema validation not exercised.');}catch(error){process.exitCode=1;await log('outcome.txt',error.stack);}finally{for(const [i,root] of [...roots].entries()){try{const dir=path.join(root,'.npm-cache/_logs');for(const file of (await readdir(dir)).slice(-10)){if(file.endsWith('.log'))await log('npm-'+i+'-'+file,await readFile(path.join(dir,file),'utf8'));}}catch{}}for(const action of cleanup){try{await action();}catch(error){console.error(error.message);process.exitCode=1;}}}
